"""
Phase 1 gate — push · trust · render.

Tests the full end-to-end flow:
  timesheet submitted → push event → ConfirmationCard rendered →
  user taps Approve → OBO token minted → stub called → receipt sealed.

This test IS the Phase 1 demo. Run it in front of stakeholders.
"""
import pytest

# Shared state across tests (flows in order through the approval lifecycle)
_state: dict = {}


async def test_timesheet_submitted_for_approval_push_arrived(e2e):
    """Northstar P1: work arrives at the user. Push carries ConfirmationCard."""
    gw = e2e["gw"]

    # TS-001 is already SUBMITTED in seed data — simulate the NATS push event
    # that would arrive when a manager's approval is requested
    r = await gw.post("/internal/push_event", json={
        "event_type": "timesheet.submitted",
        "capability_id": "acme.timesheet",
        "timesheet_id": "TS-001",
    })
    assert r.status_code == 200
    data = r.json()
    assert data["ok"] is True
    assert data["component_id"] == "ConfirmationCard"
    _state["card_hash"] = data["card_hash"]

    # Verify the push event is stored in gateway
    r = await gw.get("/internal/push_events")
    assert r.status_code == 200
    events = r.json()["events"]
    assert len(events) == 1
    assert events[0]["timesheet_id"] == "TS-001"


async def test_confirmation_card_rendered_from_entity_data(e2e):
    """INV-4: ConfirmationCard is built from resolved entity data, not model output."""
    gw = e2e["gw"]
    r = await gw.get("/internal/push_events")
    events = r.json()["events"]
    card = events[0]["card"]

    # Card must have resolved entity fields
    assert card["component_id"] == "ConfirmationCard"
    props = card["props"]
    fields = props["fields"]

    # Entity data resolved from timesheet stub — not generated by a model
    assert fields["employee.full_name"] == "Alice Smith"
    assert fields["employee.employee_id"] == "E-10001"
    assert fields["timesheet.period"] == "2025-W24"
    assert fields["timesheet.total_hours"] == 40.0
    assert props["voice_blocked"] is True
    assert props["action_id"] == "approve_timesheet_action"


async def test_user_tapped_approve(e2e):
    """P1 entry point 1: user taps Approve on push notification."""
    gw = e2e["gw"]
    r = await gw.post("/actions/approve", json={
        "timesheet_id": "TS-001",
        "user_token": "Bearer manager-E-10004",
        "user_sub": "E-10004",
        "idempotency_key": "approve-TS-001-001",
    })
    assert r.status_code == 200
    data = r.json()
    assert data["status"] == "approved"
    _state["receipt_id"] = data["receipt_id"]
    _state["receipt_committed_at"] = data["receipt_committed_at"]
    _state["scopes"] = data["scopes"]
    _state["expires_in"] = data["expires_in"]


async def test_timesheet_stub_received_approve(e2e):
    """Domain stub received POST /timesheets/{id}/approve with correct call."""
    ts = e2e["ts"]
    r = await ts.get("/internal/approved_calls")
    assert r.status_code == 200
    calls = r.json()["calls"]
    assert len(calls) == 1
    call = calls[0]
    assert call["timesheet_id"] == "TS-001"
    assert call["approved_by"] == "E-10004"
    # Token was forwarded in Authorization header
    assert call["token"] is not None
    assert call["token"].startswith("Bearer ")


async def test_obo_token_correct_scopes(e2e):
    """INV-1: OBO token has exactly timesheet.approve — no extras."""
    scopes = _state.get("scopes", [])
    assert scopes == ["timesheet.approve"], f"Expected only timesheet.approve, got: {scopes}"


async def test_obo_token_ttl_compliant(e2e):
    """INV-1: OBO token TTL ≤ 600s."""
    expires_in = _state.get("expires_in", 9999)
    assert expires_in <= 600, f"Token TTL {expires_in}s exceeds 600s maximum (INV-1)"


async def test_receipt_written_before_dispatch(e2e):
    """INV-5: receipt committed_at timestamp exists — written before dispatch."""
    receipt_id = _state.get("receipt_id")
    assert receipt_id is not None, "No receipt_id in state — test ordering issue"

    gw = e2e["gw"]
    r = await gw.get("/receipts")
    assert r.status_code == 200
    receipts = r.json()["receipts"]
    assert len(receipts) == 1

    receipt = receipts[0]
    assert receipt["id"] == receipt_id
    assert receipt["action_id"] == "approve_timesheet_action"
    assert receipt["capability_id"] == "acme.timesheet"
    assert receipt["committed_at"] is not None
    assert receipt["card_hash"] == _state.get("card_hash")


async def test_chain_hash_verified(e2e):
    """INV-5: chain hash verified — tamper-evident provenance receipt."""
    receipt_id = _state.get("receipt_id")
    assert receipt_id is not None

    gw = e2e["gw"]
    r = await gw.get(f"/receipts/{receipt_id}/verify")
    assert r.status_code == 200
    data = r.json()
    assert data["valid"] is True
    assert data["chain_intact"] is True
